name: Test Webscraper

on: 
  push:
    branches:
      - '*'
    paths:
      - 'apps/webscraper/**'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: '1.8.4'

      - name: Install Dependencies
        run: poetry install
        working-directory: apps/webscraper

      - name: Unit tests
        run: poetry run pytest -m "unit"
        working-directory: apps/webscraper

      - name: Integration tests
        run: poetry run pytest -m "integration"
        working-directory: apps/webscraper